# Generated by Django 6.0.3 on 2026-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=255)),
                ('time_min', models.IntegerField()),
                ('time_max', models.IntegerField()),
                ('age', models.IntegerField()),
                ('artist', models.CharField(blank=True, max_length=64)),
                ('designer', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
